### ISSUE TITLE
auto-save-silent does not work

### ISSUE THREAD

**Issue by LuoPX-15510486969** [manateelazycat/auto-save#1]
![image](https://user-images.githubusercontent.com/13256245/50052322-4142e480-015d-11e9-8820-5fc21a1759bb.png)

when i type in files ,it shows the save messages which make emacs so slow
ps: i have made the setting  (setq auto-save-silent t)

**Comment by manateelazycat** [comment]
You can refer to my configuration, I can't reproduce your problem.

https://github.com/manateelazycat/lazycat-emacs/blob/53daa8cb0ef2c5322ec41d17b5af0d544ec111d5/site-lisp/config/init-auto-save.el#L90
