### ISSUE TITLE
会自动保存 buffer 的内容到移除了的文件

### ISSUE THREAD

**Issue by yangjiannan2018** [manateelazycat/auto-save#10]
如题，比如在buffer 之前编辑了 A 文件，切换到另一个分支 A 文件是不存在的，当我切换到 A 文件到 buffer 中时，会自动保存buffer 中的内容到原 A 文件中

这个问题，不知道算不算是自动保存插件的问题。也有可能是 projectile 切换 project时应该自动关闭已移除的文件文件的 buffer ，避免切换到这些已移除文件的buffer 中

**Comment by manateelazycat** [comment]
当切换到新的分支时，你能在不存在的A Buffer中执行一下 (buffer-file-name) 看看minibuffer的输出是什么吗？

如果是nil，可以加一些判断来避免这种情况。

**Comment by manateelazycat** [comment]
先关闭，如果有继续反馈，欢迎重新打开。
