### ISSUE TITLE
When saving automatically, the current buffer will flash

### ISSUE THREAD

**Issue by aggronmagi** [manateelazycat/auto-save#11]
thanks for your plugins. 
(defvar auto-save-buffers-ex ()
  "auto save all buffers with save-some-buffers"
  (save-some-buffers t)) 

Using this (save-some-buffers t) will not flicker.

**Comment by manateelazycat** [comment]
I haven't this problem, please test with "emacs -Q", exclude your own configuration.

**Comment by aggronmagi** [comment]
thank you. I test with "emacs -Q", it will not flicker.
